export const portfolio = {
  projects: {
    type: "dir",
    content: "",
    projects: [
      {
        name: "Proglo Shipping",
        description: "",
        link: "",
      },
    ],
  },
  about: {
    type: "dir",
    aboutMe: {
      name: "Chance Espinosa",
      content: "",
      languages: [],
      frameworks: [],
      tools: [],
    },
    aboutPortfolio: "",
  },
  resume: {
    type: "file",
    name: "Chance Espinosa",
    location: "Las Vegas, Nevada",
    email: "chance.dev093@gmail.com",
    description: "",
    education: {
      school: "Pahrump Valley High School",
      date: "August 2013 - May 2017",
      location: "Pahrump, Nevada",
      description:
        "Graduated with a 3.6 GPA and received the Honors Diploma from Pahrump Valley High School.",
      obtained: "High School Diploma",
    },
    experience: [
      {
        company: "",
        position: "",
        date: "",
        location: "",
        bulletPoints: [""],
      },
    ],
    skills: [""],
  },
  contact: {
    type: "file",
    content: "",
    name: "Chance Espinosa",
    location: "Las Vegas, Nevada",
    email: "chance.dev093@gmail.com",
    linkedin: "",
    github: "http://github.com/Chance093",
  },
  blog: {
    type: "dir",
    content: "",
    link: "https://github.com/Chance093/markdown",
    blogs: [
      {
        title: "Managing Multiple SSH Keys for GitHub and GitLab",
        link: "https://github.com/Chance093/markdown/blob/main/HOW_TO_MANAGE_SSH_KEYS.md",
      },
    ],
  },
};

export const bootLog: string[] = [
  "[    0.000000] BIOS: VendorName ModelXYZ v1.0.0",
  "[    0.005000] Secure Boot disabled",
  "[    0.010000] Loading kernel image: /boot/vmlinuz-custom",
  "[    0.020000] Kernel command line: root=/dev/sda1 rw quiet",
  "[    0.100000] Initializing CPU…      [  OK  ]",
  "[    0.105000] Enabling memory cache… [  OK  ]",
  "[    0.110000] Parsing initramfs…     [  OK  ]",
  "[    0.200000] Mounting root filesystem: /dev/sda1  [  OK  ]",
  "[    0.250000] Activating swap…       [  OK  ]",
  "[    0.300000] Loading drivers:",
  "           ├─ network_adapter      [  OK  ]",
  "           ├─ usb_controller       [  OK  ]",
  "           ├─ storage_controller   [  OK  ]",
  "           └─ sound_card           [  OK  ]",
  "[    0.400000] Starting udev…         [  OK  ]",
  "[    0.450000] Populating device tree…[  OK  ]",
  "[    0.500000] Setting hostname: terminal-user",
  "[    0.550000] Configuring network interfaces:",
  "           ├─ eth0   … DHCP request   [  OK  ]",
  "           └─ wlan0  … disabled",
  "[    0.600000] Mounting virtual filesystems:",
  "           ├─ proc                [  OK  ]",
  "           ├─ sysfs               [  OK  ]",
  "           ├─ tmpfs               [  OK  ]",
  "           └─ devpts              [  OK  ]",
  "[    0.700000] Starting system services:",
  "           ├─ logging.service     [  OK  ]",
  "           ├─ cron.service        [  OK  ]",
  "           ├─ sshd.service        [  OK  ]",
  "           └─ firewall.service    [  OK  ]",
  "[    0.800000] Cleaning up temp files… [  OK  ]",
  "[    0.850000] Enabling user session… [  OK  ]",
  "[    0.900000] Welcome to TerminalOS 1.0.0",
  "[    0.920000] Last login: Today at 10:42",
];

export const shutdownLog: string[] = [
  "[    0.000000] Initiating shutdown sequence",
  "[    0.005000] Terminating user sessions…           [  OK  ]",
  "[    0.010000] Stopping system services:",
  "           ├─ firewall.service    … stopping       [  OK  ]",
  "           ├─ sshd.service        … stopping       [  OK  ]",
  "           ├─ cron.service        … stopping       [  OK  ]",
  "           └─ logging.service     … stopping       [  OK  ]",
  "[    0.050000] Killing remaining processes…         [  OK  ]",
  "[    0.060000] Unmounting virtual filesystems:",
  "           ├─ devpts              … unmounted     [  OK  ]",
  "           ├─ tmpfs               … unmounted     [  OK  ]",
  "           ├─ sysfs               … unmounted     [  OK  ]",
  "           └─ proc                … unmounted     [  OK  ]",
  "[    0.100000] Deactivating swap…                    [  OK  ]",
  "[    0.110000] Unmounting root filesystem: /dev/sda1 [  OK  ]",
  "[    0.120000] Stopping udev…                        [  OK  ]",
  "[    0.130000] Shutting down drivers:",
  "           ├─ sound_card           … unloaded      [  OK  ]",
  "           ├─ storage_controller   … unloaded      [  OK  ]",
  "           ├─ usb_controller       … unloaded      [  OK  ]",
  "           └─ network_adapter      … unloaded      [  OK  ]",
  "[    0.160000] Flushing file system buffers…       [  OK  ]",
  "[    0.170000] Disabling memory cache…             [  OK  ]",
  "[    0.180000] Saving BIOS settings…               [  OK  ]",
  "[    0.185000] Secure Boot state: preserving       [  OK  ]",
  "[    0.190000] Powering off hardware…              [  OK  ]",
  "[    0.195000] Goodbye from TerminalOS 1.0.0",
];

export const ascii = [
  `             ,----------------,              ,---------,`,
  `        ,-----------------------,          ,"        ,"|`,
  `      ,"                      ,"|        ,"        ,"  |`,
  `     +-----------------------+  |      ,"        ,"    |`,
  `     |  .-----------------.  |  |     +---------+      |`,
  `     |  |                 |  |  |     | -==----'|      |`,
  `     |  |   Type 'help'   |  |  |     |         |      |`,
  `     |  |   or 'ls' to    |  |  |/----|'---=    |      |`,
  `     |  |   get around!   |  |  |   ,/|==== ooo |      ;`,
  `     |  |                 |  |  |  // |(((( [33]|    ,"`,
  `     |  '-----------------'  |," .;'| |((((     |  ,"`,
  `     +-----------------------+  ;;  | |         |,"     |ASCII credit to|`,
  `        /_)______________(_/  //'   | +---------+       |   Kevin Lam   |`,
  `   ___________________________/___  ',`,
  `  /  oooooooooooooooo  .o.  oooo /,   \,"-----------`,
  ` / ==ooooooooooooooo==.o.  ooo= //   ,'\--{)B     ,"`,
  `/_==__==========__==_ooo__ooo=_/'   /___________,"`,
  `'-----------------------------'"`,
];

export const commandsDescList = [
  "* ls - Lists the files and directories in the current directory.",
  "* cd <dir> - Changes the current directory to <dir>. Use `cd ..` to go up one level.",
  "* cat <file> - Prints the contents of <file> to the terminal.",
  "* clear - Clears all text from the terminal window.",
  "* help - Shows a brief introduction and usage tips.",
  "* commands - Displays a full list of available commands.",
  "* theme - Switches between different color/font themes.",
  "* pwd - Prints the “present working directory” path.",
  "* exit - Ends the session and exits the website",
  "* date - Prints the current date and time.",
  "* easymode - Enables “easy navigation” mode—use your arrow keys and Enter to browse directories and open files without typing commands.",
];

export const helpCommandList = [
  "Welcome to my terminal portfolio. Here you can explore my projects, view my code samples, and learn more about my skills all through a command-line interface.",
  "If you’re comfortable with a UNIX-style terminal, try running `ls` to list the available directories and files.",
  "If you’re new to this interface or want to see all the commands that are available, type `commands` and press Enter to view a full list of supported commands.",
  "If you find navigating terminals to be too difficult, check out the `easymode` command I made.",
  "Feel free to leave feedback by opening an issue on the GitHub repo or emailing me at chance.dev093@gmail.com.",
];
